### ISSUE TITLE
Branches endpoint throws exception

### ISSUE THREAD

**Issue by tom-sinclair** [dezrez/DezrezCoreAPI#65]
Ultimately, I'm trying to get all milestones (`/agency/progression/getallmilestones`), but that endpoint requires `progressorRoleId`, as I'm not sure what this is and where to get it, I tried to access all branches to get hold of the roles attached to it, as one of your guides infers all roles belong to a branch. When I hit this endpoint (`/agency/branches`), an exception is thrown:
```json
{#4395
  +"Message": "An error has occurred."
  +"ExceptionMessage": "An error occurred when trying to create a controller of type 'AgencyController'. Make sure that the controller has a parameterless public constructor."
  +"ExceptionType": "System.InvalidOperationException"
  +"StackTrace": """
       at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType)\r\n
       at System.Web.Http.Controllers.HttpControllerDescriptor.CreateController(HttpRequestMessage request)\r\n
       at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
    """
  +"InnerException": {#4382
    +"Message": "An error has occurred."
    +"ExceptionMessage": "An exception was thrown while invoking the constructor 'Void .ctor(Dezrez.Rezi.Abstractions.Core.Logging.ILogger, Dezrez.Rezi.Abstractions.Core.User.IAccountingUserContext, NHibernate.IInterceptor, Dezrez.Rezi.Abstractions.Services.Application.Configuration.IConfigurationApplicationService)' on type 'AccountingUnitOfWork'. ---> Could not map the current identity to a user! (See inner exception for details.)"
    +"ExceptionType": "Autofac.Core.DependencyResolutionException"
    +"StackTrace": """
         at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()\r\n
         at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)\r\n
         at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)\r\n
         at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)\r\n
         at Autofac.Core.Resolving.InstanceLookup.Execute()\r\n
         at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)\r\n
         at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()\r\n
         at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)\r\n
         at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)\r\n
         at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)\r\n
         at Autofac.Core.Resolving.InstanceLookup.Execute()\r\n
         at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)\r\n
         at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()\r\n
         at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)\r\n
         at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)\r\n
         at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)\r\n
         at Autofac.Core.Resolving.InstanceLookup.Execute()\r\n
         at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)\r\n
         at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()\r\n
         at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)\r\n
         at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)\r\n
         at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)\r\n
         at Autofac.Core.Resolving.InstanceLookup.Execute()\r\n
         at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)\r\n
         at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()\r\n
         at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)\r\n
         at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)\r\n
         at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)\r\n
         at Autofac.Core.Resolving.InstanceLookup.Execute()\r\n
         at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)\r\n
         at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()\r\n
         at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)\r\n
         at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)\r\n
         at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)\r\n
         at Autofac.Core.Resolving.InstanceLookup.Execute()\r\n
         at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)\r\n
         at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()\r\n
         at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)\r\n
         at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)\r\n
         at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)\r\n
         at Autofac.Core.Resolving.InstanceLookup.Execute()\r\n
         at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)\r\n
         at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()\r\n
         at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)\r\n
         at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)\r\n
         at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)\r\n
         at Autofac.Core.Resolving.InstanceLookup.Execute()\r\n
         at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)\r\n
         at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()\r\n
         at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)\r\n
         at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)\r\n
         at Autofac.Core.Resolving.InstanceLookup.Execute()\r\n
         at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)\r\n
         at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)\r\n
         at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)\r\n
         at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)\r\n
         at Autofac.Integration.WebApi.AutofacWebApiDependencyScope.GetService(Type serviceType)\r\n
         at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.GetInstanceOrActivator(HttpRequestMessage request, Type controllerType, Func`1& activator)\r\n
         at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType)
      """
    +"InnerException": {#4379
      +"Message": "An error has occurred."
      +"ExceptionMessage": "Could not map the current identity to a user!"
      +"ExceptionType": "System.Exception"
      +"StackTrace": """
           at Dezrez.Rezi.Services.Domain.UserMapper.UserMapperDomainService.GetPersonFromCurrentPrincipal() in C:\agent\_work\108\s\Dezrez.Rezi.Services\Dezrez.Rezi.Services.Domain\UserMapper\UserMapperDomainService.cs:line 125\r\n
           at Dezrez.Rezi.Core.User.AccountingUserContext.LookUpAccountingSystemIDAndSetPersonId() in C:\agent\_work\108\s\Dezrez.Rezi.Core\Dezrez.Rezi.Core\User\AccountingUserContext.cs:line 63\r\n
           at Dezrez.Rezi.Core.User.AccountingUserContext.get_AccountingSystemId() in C:\agent\_work\108\s\Dezrez.Rezi.Core\Dezrez.Rezi.Core\User\AccountingUserContext.cs:line 74\r\n
           at Dezrez.Rezi.Repository.NHibernate.UnitOfWork.AccountingUnitOfWork..ctor(ILogger logger, IAccountingUserContext userContext, IInterceptor interceptor, IConfigurationApplicationService configurationApplicationService) in C:\agent\_work\108\s\Dezrez.Rezi.Repository.NHibernate\UnitOfWork\AccountingUnitOfWork.cs:line 46\r\n
           at lambda_method(Closure , Object[] )\r\n
           at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
        """
    }
  }
}
```

Any help would be appreciated.

**Comment by ajonesgh** [comment]
Hi Tom

The ProgressionRoleId will be the TenantRoleId or PurchasingRoleId which can be found on the property marketing role

Any further issues please let us know

Thanks
Adam

**Comment by tom-sinclair** [comment]
How do I get the property marketing role? Can you point me to the endpoints I would need to hit to get the information I need, the only information I have is the agency IDs

Are there any walkthrough guides on how to use your API or what the data structure looks like?

**Comment by ajonesgh** [comment]
If you don't know the id's up front you can do a search using the global search endpoint https://api.dezrez.com/Help/Api/GET-api-globalsearch-properties

Here is the API help page https://api.dezrez.com/help

**Comment by tom-sinclair** [comment]
Is a role unique to a property?

**Comment by ajonesgh** [comment]
Yes. Once a property is valued a Selling/Letting role is created on the Property.Roles collection
